import re
import unittest
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
APP=(ROOT/'app.js').read_text()
INDEX=(ROOT/'index.html').read_text()
README=(ROOT/'README.md').read_text()
WORKER=(ROOT/'service-worker.js').read_text()
PERSISTENCE=(ROOT/'persistence.js').read_text()
HOT=APP[APP.index('function normalizeEffectiveHit'):APP.index('function createWeaponRuleResolution')]

class HotWeaponRuleTests(unittest.TestCase):
    def test_01_version(self): self.assertIn("const APP_VERSION = '8.6.55';",APP); self.assertIn('V8.6.55',INDEX)
    def test_02_handler(self): self.assertIn("hot:{mode:'automatic',phase:'after-weapon-use'}",APP)
    def test_03_automatic(self): self.assertIn("hot:{mode:'automatic'",APP)
    def test_04_supported(self): self.assertNotIn('Hot is not yet supported by the Guide.',APP)
    def test_05_summary_once(self): self.assertEqual(APP.count("Hot: After this weapon is used, the Guide will roll one D6."),1)
    def test_06_non_hot_guard(self): self.assertIn("if(!profile||!weaponHasRule(profile,'hot'))return null",HOT)
    def test_07_single_hook(self): self.assertIn('finishPlayerAttackResolution(stage)',APP)
    def test_08_after_commit(self): self.assertLess(APP.index('if(applyPendingPlayerDamage(stage))return;'),APP.index('finishPlayerAttackResolution(stage);'))
    def test_09_roll_one_damage(self): self.assertIn('record.roll*2:0',HOT)
    def test_10_roll_two_damage(self): self.assertIn('record.roll<record.effectiveHit',HOT)
    def test_11_equal_no_damage(self): self.assertIn('record.roll<record.effectiveHit?',HOT)
    def test_12_six_no_damage(self): self.assertIn('hit<=6',HOT)
    def test_13_effective_hit(self): self.assertIn('effectiveHit:normalizeEffectiveHit(profile.hit)',HOT)
    def test_14_injured_effective_hit(self): self.assertIn('record.roll<record.effectiveHit',HOT)
    def test_15_direct_damage(self): self.assertIn('state.playerWounds[record.attackerId]=after',HOT); self.assertNotIn('defenseDice',HOT)
    def test_16_player_wounds(self): self.assertIn("record.attackerSide==='player'",HOT)
    def test_17_clamped(self): self.assertIn('Math.max(0,before-damage)',HOT)
    def test_18_player_incapacitation(self): self.assertIn('incapacitated=after===0',HOT)
    def test_19_player_casualty(self): self.assertIn('state.playerCasualtyIds.push(record.attackerId)',HOT)
    def test_20_target_preserved(self): self.assertIn('The shooting attack was preserved',HOT)
    def test_21_blast_once(self): self.assertIn('showMultiTargetAttackSummary(completed',APP)
    def test_22_torrent_once(self): self.assertIn("torrent:{mode:'guided'",APP)
    def test_23_no_target_identity(self): self.assertNotIn('targetId',APP[APP.index('function createHotResolution'):APP.index('function applyHotDamage')])
    def test_24_skipped_targets(self): self.assertIn('filter(result=>result?.committed&&!result.skipped)',APP)
    def test_25_cancel_no_hot(self): self.assertNotIn('completeShootingWeaponUse',APP[APP.index("$('#cancelPendingAttack').onclick"):APP.index('if(result){',APP.index("$('#cancelPendingAttack').onclick"))])
    def test_26_back_no_hot(self): self.test_25_cancel_no_hot()
    def test_27_pending_persisted(self): self.assertIn('hotResolution:null',APP); self.assertIn('normalizeHotResolution(raw.hotResolution)',APP)
    def test_28_roll_preserved(self): self.assertIn('if(!Number.isInteger(record.roll))',HOT)
    def test_29_damage_once(self): self.assertIn('if(record.applied)return record',HOT)
    def test_30_update_preserved(self): self.assertIn('state.hotResolution=record;save()',HOT)
    def test_31_rapid_roll(self): self.assertIn('if(state.hotResolution?.acknowledged)return',HOT)
    def test_32_rapid_damage(self): self.assertIn('if(!record.applied)',HOT)
    def test_33_history_once(self): self.assertIn('if(!record.historyRecorded)',HOT)
    def test_34_no_damage_history(self): self.assertIn('suffered no damage.',HOT)
    def test_35_npo_same_rule(self): self.assertIn("attackerSide:'npo'",APP); self.assertIn('applyHotDamage(record)',HOT)
    def test_36_npo_incapacitation(self): self.assertIn("attacker.battlefieldState='out-of-action'",HOT)
    def test_37_duplicate_hot(self): self.assertIn('duplicateCount>1',HOT)
    def test_38_invalid_hit(self): self.assertIn("status:'error'",HOT); self.assertIn('Effective Hit stat is unavailable',HOT)
    def test_39_reduced_motion_outcome_stored(self): self.assertIn('dieHtml({value:record.roll',HOT)
    def test_40_other_rules(self): self.assertIn("lethal:{mode:'automatic'",APP); self.assertIn("piercing:{mode:'automatic'",APP)
    def test_41_single_unchanged_guard(self): self.assertIn("const result=shootResults[0]",APP)
    def test_42_multi_completed(self): self.assertIn('completed:orderedTargetIds.length===0',APP); self.assertIn('finishWeaponUse',APP)
    def test_43_save_version(self): self.assertIn('const SAVE_VERSION = 3;',PERSISTENCE)
    def test_44_release(self): self.assertTrue(README.startswith('# Tomb World Solo Guide v8.6.55')); self.assertIn("const APP_VERSION = '8.6.55';",WORKER)
    def test_45_history_uses_transaction_id(self): self.assertIn('entry.transactionId===record.id',HOT); self.assertIn('transactionId:record.id',HOT)
    def test_46_npo_recovery_commits_pending_action(self): self.assertIn('function resumePersistedHotContinuation',HOT); self.assertIn('commitNpoAction({actionId:pending.id',HOT)
    def test_47_npo_recovery_clears_completed_sequence(self): self.assertIn('state.weaponRuleResolution=null;',HOT)
    def test_48_reduced_motion_skips_animation(self): self.assertIn("matchMedia('(prefers-reduced-motion: reduce)').matches",HOT); self.assertIn("reducedMotion?'settled':'animated-roll'",HOT)
    def test_49_summary_distinguishes_hot_damage(self): self.assertIn('hot-attack-summary',APP); self.assertIn('Attacker suffered ${hot.damage} damage',APP)

if __name__=='__main__': unittest.main()
