import { DASHBOARD_CONFIG } from './shared/dashboard-config.js';
import { DASHBOARD_PROTOCOL_VERSION, DASHBOARD_MESSAGE_TYPES, safeParseDashboardJson, validateDashboardMessage } from './shared/dashboard-protocol.js';
import { readPairingFragment, clearPairingFragment, decodePairingData, serializePairingData } from './shared/pairing-codec.js';
import { renderQrCode } from './shared/qr-utils.js';

const status = document.querySelector('[data-dashboard-status]');
const pairing = document.querySelector('[data-dashboard-pairing]');
const responseOutput = document.querySelector('[data-response-output]');
const verification = document.querySelector('[data-verification]');
function setStatus(value) { status.textContent = value; }
function waitForIce(peer) { if (peer.iceGatheringState === 'complete') return Promise.resolve(); return new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('ICE gathering timed out.')), DASHBOARD_CONFIG.connectionTimeoutMs); peer.addEventListener('icegatheringstatechange', function change() { if (peer.iceGatheringState === 'complete') { clearTimeout(timer); peer.removeEventListener('icegatheringstatechange', change); resolve(); } }); }); }
async function codeFor(nonce) { const bytes = new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(`tomb-world-dashboard:${nonce}`))); return (((bytes[0] << 16) | (bytes[1] << 8) | bytes[2]) % 1000000).toString().padStart(6, '0').replace(/(\d{3})(\d{3})/, '$1 $2'); }
async function pair() {
  const encoded = readPairingFragment(location.hash, 'offer');
  if (!encoded) { setStatus('Open the dashboard URL generated by the game device.'); return; }
  clearPairingFragment();
  try {
    setStatus('Creating dashboard response…');
    const offer = await decodePairingData(encoded, { expectedType: 'offer', expectedSdpType: 'offer' });
    const peer = new RTCPeerConnection({ iceServers: DASHBOARD_CONFIG.iceServers });
    peer.ondatachannel = event => {
      const channel = event.channel;
      if (channel.label !== 'tomb-world-dashboard') { channel.close(); return; }
      channel.onopen = () => channel.send(JSON.stringify({ protocolVersion: DASHBOARD_PROTOCOL_VERSION, type: DASHBOARD_MESSAGE_TYPES.DASHBOARD_READY }));
      channel.onmessage = messageEvent => { const message = safeParseDashboardJson(messageEvent.data); if (!validateDashboardMessage(message).valid || message.type !== DASHBOARD_MESSAGE_TYPES.HELLO) return; channel.send(JSON.stringify({ protocolVersion: DASHBOARD_PROTOCOL_VERSION, type: DASHBOARD_MESSAGE_TYPES.HELLO_ACK })); setStatus('Connected'); pairing.hidden = true; verification.hidden = false; };
      channel.onclose = () => setStatus('Connection interrupted');
    };
    await peer.setRemoteDescription({ type: offer.sdpType, sdp: offer.sdp });
    await peer.setLocalDescription(await peer.createAnswer()); await waitForIce(peer);
    const answer = await serializePairingData({ protocolVersion: DASHBOARD_PROTOCOL_VERSION, type: 'answer', nonce: offer.nonce, createdAt: Date.now(), expiresAt: offer.expiresAt, sdpType: 'answer', sdp: peer.localDescription.sdp, label: offer.label });
    responseOutput.value = answer;
    await renderQrCode(document.querySelector('[data-response-qr]'), answer, 'Scan this response QR code with the game device.');
    pairing.hidden = false; verification.querySelector('strong').textContent = await codeFor(offer.nonce);
    document.querySelector('[data-copy-response]').onclick = async () => { await navigator.clipboard.writeText(answer); setStatus('Response copied. Return to the game device.'); };
    setStatus('Waiting for the game device to scan or paste this response.');
  } catch (error) { setStatus(error.message || 'The pairing link could not be read.'); }
}
pair();
